name: helm build
run-name: Being run by ${{ github.actor }}
on: [push]
jobs:
  helm-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      - run: ls -la
      - run: ls -la ~
      - run: ls -la /
      - run: tree
      - run: tree .
      - run: /home
      - run: /home/runner
      - run: /home/runner/work
      - run: /home/runner/work/nginx-helm
      - run: /home/runner/work/nginx-helm/nginx-helm
      - run: whoami
      - run: pwd
