name: helm build
run-name: Being run by ${{ github.actor }}
on: [push]
jobs:
  helm-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      - run: ls -la
      - run: ls -la /
      - run: whoami
      - run: pwd
