name: helm build
run-name: Being run by ${{ github.actor }}
on: [push]
jobs:
  helm-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
#      - run: echo "Hello World!"
      - run: ls -la
      - name: install using helm
        run: helm upgrade --install my-app .
#      - run: ls -la ~
#      - run: ls -la /
#      - run: tree
#      - run: tree .
##      - run: tree /home
#      - run: tree /home/runner
#      - run: tree /home/runner/work
#      - run: tree /home/runner/work/nginx-helm
#      - run: tree /home/runner/work/nginx-helm/nginx-helm
#      - run: whoami
#      - run: pwd
