name: helm build
run-name: Being run by ${{ github.actor }}
on: [push] # just for testing, should be some form of [release]
jobs:
  helm-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - run: ls -la
      - name: install using helm
        run: helm package .
      - run: ls -la
      - name: adding repo
        run: helm repo add talend-public https://talend.github.io/helm-charts-public/stable
      - name: searching for charts
        run: helm search repo talend-public
      - name: access own helm repository
        run: helm repo add tw https://tony-waters.github.io/helm-charts/
      - name: push to registry
        run: echo "Pushing to registry"

